name: Add team label

on:
  pull_request:
    types:
      - opened

jobs:
  add-team-label:
    uses: ./.github/workflows/add-team-label.yml
    secrets:
      TEAM_LABEL_TOKEN: ${{ secrets.TEAM_LABEL_TOKEN }}
      PR_LABEL_TOKEN: ${{ secrets.PR_LABEL_TOKEN }}
