name: Add team label

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  add-team-label:
    uses: ./.github/workflows/add-team-label.yml
    secrets: inherit
