name: Main

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml
