name: On delete

on:
  delete:

jobs:
  on-delete:
    name: On delete
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "${{ github.event.ref }} - ${{ github.event.ref_type }}"
