name: Record PR removal

on: delete

jobs:
  record-pr-removal:
    if: github.event.ref_type == 'branch' && startswith(github.event.ref, 'remove/')
    name: Record PR removal
    runs-on: ubuntu-latest
    steps:
      - name: Get status of deleted branch
        id: get-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          status=$(gh api repos/${{ github.repository }}/commits/${{ github.event.ref }}/status --jq '.state')
          echo "The status of ${{ github.event.ref }} is $status."
          echo 'STATUS='"$status" >> "$GITHUB_OUTPUT"

      - name: Write data to google sheets
        if: steps.get-status.outputs.STATUS == 'failure'
        run: |
          echo "Writing to google sheets"
